---
title: "RNAseq Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rnaseq_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(simpleExpressionProcessing)
```

```{r}
accession <- "GSE158395"

# Get GEO data
gse <- MetaIntegrator::getGEOData(accession)
# Need to fix some attributes of MetaIntegrator object for RNAseq compatibility
gse <- fixMetaIntegratorForRNAseq(gse) 

# Get GEO supplemental data, including raw data, and process
## withr used to create a tempdir for supplemental files for purpose of demo
withr::with_tempdir({
  getRNAcountMatrixNCBI(accession)
  reprocess_output <- processRNA(sprintf("./%s", accession))
})

# Add raw and reprocessed expression matrices to original MetaIntegrator
# GEO object
gse <- addRawExprMatrix(gse, reprocess_output$raw_expression, mode = "rnaseq")
gse <- addReprocessedExprMatrix(gse, reprocess_output$normalized_expression, mode = "rnaseq")

# Visualize effect of processing
geoAllBoxplots(gse)
```

